version: '3.10'

services:
  web:
    image: "djocketry-boiler:dev"

    build:
      target: development_build
      context: .
      cache_from:
        - "djocketry-boiler:dev"
        - "djocketry-boiler:latest"
      args:
        DJANGO_ENV: development
    command: python -Wd manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.4-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]

volumes:
  postgres_data: